# -*- coding: utf-8 -*-
"""croprec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19eibYcLCbsX09C6MA9_SKy8ppOoNa1cn
"""

from __future__ import print_function
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv('Crop_recommendation.csv')
features = df[['N', 'P','K','temperature', 'humidity', 'ph', 'rainfall']]
target = df['label']
#features = df[['temperature', 'humidity', 'ph', 'rainfall']]
labels = df['label']
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(features,target,test_size = 0.2,random_state =2)
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=20, random_state=0)
sv=RF.fit(Xtrain,Ytrain)
# predicted_values = RF.predict(Xtest)
# x = metrics.accuracy_score(Ytest, predicted_values)
# print("RF's Accuracy is: ", x)
#print(classification_report(Ytest,predicted_values))
pickle.dump(sv, open('croprec.pkl', 'wb'))